name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch: # 允许手动触发

env:
  TZ: Asia/Shanghai
  DEPLOY_BRANCH: gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # 设置超时时间

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 升级到最新版本
        with:
          fetch-depth: 0 # 获取所有历史记录，用于 git describe

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm' # 启用 pnpm 缓存

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build project
        run: |
          export NODE_OPTIONS="--max_old_space_size=8192"
          pnpm run build
        env:
          NODE_ENV: production

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global init.defaultBranch $DEPLOY_BRANCH

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # 使用专门的部署 action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 使用内置 token，无需额外配置
          publish_dir: ./docs/.vuepress/dist
          force_orphan: true # 保持 gh-pages 分支的清洁
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'